import {
  HandCoins, GraduationCap, Shield, House, Key, Heart,
  Accessibility, Zap, Target, ChartBar, Scale, Handshake, ShieldCheck,
  Map, Award, Landmark, Building2, Users, HeartPulse, Monitor, Church,
  HeartHandshake, Building, HandHelping, UserCheck, MessageCircle,
  Briefcase, Headphones, ShoppingBag, Utensils, Truck, Wrench, User,
  CircleCheck, BookOpen, TrendingUp, Sliders, DollarSign, FileText,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  'hand-coins': HandCoins,
  'graduation-cap': GraduationCap,
  'shield': Shield,
  'home': House,
  'key': Key,
  'heart': Heart,
  'accessibility': Accessibility,
  'zap': Zap,
  'target': Target,
  'bar-chart-3': ChartBar,
  'scale': Scale,
  'handshake': Handshake,
  'shield-check': ShieldCheck,
  'map': Map,
  'award': Award,
  'landmark': Landmark,
  'building-2': Building2,
  'users': Users,
  'heart-pulse': HeartPulse,
  'monitor': Monitor,
  'church': Church,
  'heart-handshake': HeartHandshake,
  'building': Building,
  'hand-helping': HandHelping,
  'user-check': UserCheck,
  'message-circle': MessageCircle,
  'briefcase': Briefcase,
  'headphones': Headphones,
  'shopping-bag': ShoppingBag,
  'utensils': Utensils,
  'truck': Truck,
  'wrench': Wrench,
  'user': User,
  'check-circle': CircleCheck,
  'book-open': BookOpen,
  'trending-up': TrendingUp,
  'sliders': Sliders,
  'dollar-sign': DollarSign,
  'file-text': FileText,
}
